/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JComboBox;
import javax.swing.JTextField;

/**
 *
 * @author Konjem_Family
 */
public class tambahPasienInap extends javax.swing.JFrame {

    /**
     * Creates new form tambahPasienInap
     */
    public tambahPasienInap() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        labPasienInap = new javax.swing.JLabel();
        labKelas = new javax.swing.JLabel();
        labLantai = new javax.swing.JLabel();
        labNamaPasien = new javax.swing.JLabel();
        labNamaDokter = new javax.swing.JLabel();
        labPenyakit = new javax.swing.JLabel();
        btnOk = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        boxKelas = new javax.swing.JComboBox<>();
        boxLantai = new javax.swing.JComboBox<>();
        tfNoKamar = new javax.swing.JTextField();
        tfPenyakit = new javax.swing.JTextField();
        btnMainMenu = new javax.swing.JButton();
        labLantai1 = new javax.swing.JLabel();
        boxNamaDokter = new javax.swing.JComboBox<>();
        boxNamaPasien = new javax.swing.JComboBox<>();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        labPasienInap.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        labPasienInap.setText("Tambah Pasien Inap");

        labKelas.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labKelas.setText("Kelas");

        labLantai.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labLantai.setText("Lantai");

        labNamaPasien.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labNamaPasien.setText("Nama Pasien");

        labNamaDokter.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labNamaDokter.setText("Nama Dokter");

        labPenyakit.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labPenyakit.setText("Penyakit");

        btnOk.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnOk.setText("Ok");

        btnReset.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        btnReset.setText("Reset");

        boxKelas.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Kelas", "A", "B", "C" }));

        boxLantai.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        boxLantai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih Lantai", "Lantai 1", "Lantai 2 ", "Lantai 3" }));

        btnMainMenu.setIcon(new javax.swing.ImageIcon("D:\\Java\\Tugas Besar PBO\\Home.png")); // NOI18N

        labLantai1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        labLantai1.setText("No. Kamar");

        boxNamaDokter.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        boxNamaPasien.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(210, 210, 210)
                        .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                        .addComponent(btnMainMenu))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(58, 58, 58)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(labNamaPasien)
                            .addComponent(labPenyakit)
                            .addComponent(labLantai)
                            .addComponent(labKelas)
                            .addComponent(labNamaDokter)
                            .addComponent(labLantai1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(boxKelas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tfNoKamar)
                            .addComponent(boxLantai, javax.swing.GroupLayout.Alignment.LEADING, 0, 258, Short.MAX_VALUE)
                            .addComponent(tfPenyakit)
                            .addComponent(boxNamaDokter, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(boxNamaPasien, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(78, 78, 78)
                .addComponent(labPasienInap)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btnMainMenu)
                .addGap(1, 1, 1)
                .addComponent(labPasienInap)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(labKelas)
                    .addComponent(boxKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(boxLantai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labLantai))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfNoKamar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labLantai1))
                        .addGap(26, 26, 26)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNamaPasien)
                            .addComponent(boxNamaPasien, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(76, 76, 76)
                        .addComponent(labPenyakit))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(labNamaDokter)
                            .addComponent(boxNamaDokter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addComponent(tfPenyakit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public String getBoxKelas() {
        return boxKelas.getSelectedItem().toString();
    }
    
    public String getBoxLantai() {
        return boxLantai.getSelectedItem().toString();
    }
    
    public int getNoKamar() {
        return Integer.parseInt(tfNoKamar.getText()) ;
    }
    
    public JComboBox<String> getDokterSelected() {
        return boxNamaDokter;
    }
    
    public JComboBox<String> getPasienSelected() {
        return boxNamaPasien;
    }
    
    public String getPenyakit() {
        return tfPenyakit.getText();
    }
    
    public Object getBtnOk(){
        return btnOk;
    }
    
    public Object getBtnReset(){
        return btnReset;
    }
    
    public Object getBtnMainMenu(){
        return btnMainMenu;
    }
    
    public void reset(){
        boxKelas.setSelectedIndex(0);
        boxLantai.setSelectedIndex(0);
        tfNoKamar.setText("");
        boxNamaPasien.setSelectedIndex(0);
        boxNamaDokter.setSelectedIndex(0);
        tfPenyakit.setText("");
    }
    
    public void addListen (ActionListener a){
        this.btnOk.addActionListener(a);
        this.btnReset.addActionListener(a);
        this.btnMainMenu.addActionListener(a);
    }
    
//    public String getNamaDokter() {
//        return NamaDokter.getText();
//    }
//
//    public String getNamaPasien() {
//        return NamaPasien.getText();
//    }

    
    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(tambahPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(tambahPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(tambahPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(tambahPasienInap.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new tambahPasienInap().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> boxKelas;
    private javax.swing.JComboBox<String> boxLantai;
    private javax.swing.JComboBox<String> boxNamaDokter;
    private javax.swing.JComboBox<String> boxNamaPasien;
    private javax.swing.JButton btnMainMenu;
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnReset;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JLabel labKelas;
    private javax.swing.JLabel labLantai;
    private javax.swing.JLabel labLantai1;
    private javax.swing.JLabel labNamaDokter;
    private javax.swing.JLabel labNamaPasien;
    private javax.swing.JLabel labPasienInap;
    private javax.swing.JLabel labPenyakit;
    private javax.swing.JTextField tfNoKamar;
    private javax.swing.JTextField tfPenyakit;
    // End of variables declaration//GEN-END:variables

    public Object getTambah() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
